version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=pass
      - MYSQL_PASSWORD=dav
      - MYSQL_DATABASE=app